services:
  app:
    image: todo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:80 # 3000:3000
    container_name: todo-frontend